# Generated by Django 3.1.4 on 2021-01-15 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=15)),
                ('username', models.CharField(blank=True, max_length=264, null=True)),
                ('full_name', models.CharField(blank=True, max_length=264, null=True)),
                ('designation', models.CharField(blank=True, max_length=264, null=True)),
                ('address_1', models.TextField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('healthcard', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_join', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='no-name.jpg', null=True, upload_to='profile')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log in the site', verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treatea as active', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponId', models.CharField(default=0, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
