# Generated by Django 3.1.4 on 2021-01-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='healthcard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
