# Generated by Django 3.1.4 on 2021-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0002_auto_20210115_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponId',
            field=models.CharField(max_length=15),
        ),
    ]
