# Generated by Django 3.1.4 on 2021-01-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0003_auto_20210115_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
