# Generated by Django 3.1.4 on 2021-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
